POST http://localhost:3000/bank-account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoid2V4bGVya2ltYmVybHk5MEBnbWFpbC5jb20iLCJpc0FnZW50IjpmYWxzZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJ2ZW5kb3IiLCJpYXQiOjE3NzkzNjY0OTAsImV4cCI6MTc3OTM3MDA5MCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.hETTejFasP1SNx0eTHMTcTQJpAG98J1RUHiGzlpSKF8

{
    "bankCode": "058",
    "accountNumber": "0121899311"
}

GET http://localhost:3000/bank-account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJseWRpYW1jZ2lsbDIyQGdtYWlsLmNvbSIsImlzQWdlbnQiOnRydWUsImlzVmVuZG9yIjpmYWxzZSwiaWF0IjoxNzY3OTY2ODMwLCJleHAiOjE3Njc5NzA0MzAsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Ui3GAwU5txumAT9QlJ5OojADlYduF_8YjToFCfxGRWo

PATCH http://localhost:3000/bank-account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJseWRpYW1jZ2lsbDIyQGdtYWlsLmNvbSIsImlzQWdlbnQiOnRydWUsImlzVmVuZG9yIjpmYWxzZSwiaWF0IjoxNzY3OTY2ODMwLCJleHAiOjE3Njc5NzA0MzAsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Ui3GAwU5txumAT9QlJ5OojADlYduF_8YjToFCfxGRWo
Content-Type: application/json

{
    "bankCode": "999991",
    "accountNumber": "9030381626"
}


GET http://localhost:3000/bank-account/banks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3NjI0ODczOSwiZXhwIjoxNzc2MjUyMzM5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.QrAe4W7p5U0MnzKMFx6neBGiOIMJGkCoPrk8HSno8nw


POST http://localhost:3000/bank-account/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3NjI1MzQ2MCwiZXhwIjoxNzc2MjU3MDYwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.WjyiGf6S_KvXuZwrBVbs4d986Bw2yWMtciSTdflQrL8
Content-Type: application/json

{
    "bankCode": "058",
    "accountNumber": "0121899311"
}