POST http://localhost:3000/agent/create-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoibHlkaWFtY2dpbGwyMkBnbWFpbC5jb20iLCJyb2xlIjoiYWdlbnQiLCJpYXQiOjE3NjQwNjc2OTMsImV4cCI6MTc2NDA3MTI5MywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.1CB85lHGcYdZY4zIMduPSZZNVDZG7ZwFCv9x4fUMaPY

{
    "businessName": "Benson Logistics",
    "address": "123 Uniben school gate road, Benin city",
    "bio": "Experienced agent specializing in deliveries in the southern part of Nigeria",
    "statesCovered": ["imo", "edo", "delta"]
}


POST http://localhost:3000/agent-kyc/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwicm9sZSI6ImFnZW50IiwiaWF0IjoxNzYwMDA5NTUyLCJleHAiOjE3NjAwMTMxNTIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Sez_JguItZssgcSjAliuQK0Hkbci9UKq1DcuRwp8HW8

{
    "nin": "12345678901",
    "bvn": "33211897899"
}

POST http://localhost:3000/agent-bank-account/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwicm9sZSI6ImFnZW50IiwiaWF0IjoxNzYwMTAxMzQ5LCJleHAiOjE3NjAxMDQ5NDksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.xpKoS4e3ZTSFX2WoBLgEJMD9cVJWuUFCBCdzlS98zdk

{
    "bankCode": "058",
    "accountNumber": "0121899311"
}