POST http://localhost:3000/quotes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwicm9sZSI6ImFnZW50IiwiaWF0IjoxNzY0ODczNTI2LCJleHAiOjE3NjQ4NzcxMjYsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.4RegDsUUwSLYHAyTJu9QXSoW33qJm9c_MYyPzGm91ng

{
    "requestId": 28,
    "deliveryCosts": [
        {
            "deliveryId":55,
            "cost": 1200
        },
        {
            "deliveryId": 56,
            "cost": 1000
        }
    ]
}


POST http://localhost:3000/quotes/18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoibWFudWVsZ2VldGVjaEBnbWFpbC5jb20iLCJyb2xlIjoidmVuZG9yIiwiaWF0IjoxNzY0ODc0MTA3LCJleHAiOjE3NjQ4Nzc3MDcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.qUEavWRwPaLyvWCPOhXURmyMzPuGA-tpm3KdEWPZWNc