GET http://localhost:3000/quotes/view/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3OTI2NzIwOCwiZXhwIjoxNzc5MjcwODA4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.Q3LL90D6NMfOIwZ4MLX88ihEnfwnSw59g9eAKmMJpTE

GET http://localhost:3000/quotes/agent 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJseWRpYW1jZ2lsbDIyQGdtYWlsLmNvbSIsImlzQWdlbnQiOnRydWUsImlzVmVuZG9yIjpmYWxzZSwiYWN0aXZlUm9sZSI6ImFnZW50IiwiaWF0IjoxNzc3NDc0MDg0LCJleHAiOjE3Nzc0Nzc2ODQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.ClX1sjct_Xkbst-ska0Q_FOIfwc7nfOF9XC8bBQsZj0

GET http://localhost:3000/quotes/check-submission/56
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoiZW1tYW51ZWxAZGlsaXZhbHkuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOmZhbHNlLCJhY3RpdmVSb2xlIjoiYWdlbnQiLCJpYXQiOjE3Nzk0NTU4NjYsImV4cCI6MTc3OTQ1OTQ2NiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.R5jc7EGbdJONSndC0ov34hnWJgQPN3kwQnp1_U1EnNg