POST http://localhost:3000/quotes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJseWRpYW1jZ2lsbDIyQGdtYWlsLmNvbSIsImlzQWdlbnQiOnRydWUsImlzVmVuZG9yIjpmYWxzZSwiYWN0aXZlUm9sZSI6ImFnZW50IiwiaWF0IjoxNzc3NzE4ODQ5LCJleHAiOjE3Nzc3MjI0NDksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.1RIsamkgY6oEmXqiwYoTShteM0Y77yVVzB3skDXBKmM

{
    "requestId": 29,
    "deliveryCosts": [
        {
            "deliveryId":85,
            "cost": 500
        }
        // {
        //     "deliveryId": 66,
        //     "cost": 200
        // },
        // {
        //     "deliveryId": 67,
        //     "cost": 200
        // },
        // {
        //     "deliveryId": 68,
        //     "cost": 1200
        // }
    ]
}


POST http://localhost:3000/quotes/31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3ODE2MDg2NiwiZXhwIjoxNzc4MTY0NDY2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.5T6GoyuYxh-xKyd7LyfDcodg3Xjx-KFaIstd44525wA

POST http://localhost:3000/quotes/40/pay
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3ODE2NDUxOSwiZXhwIjoxNzc4MTY4MTE5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.SuX8Pzm8QK3vYOCti5O1kil1-K4k8VYsdEApVs1rxhI