GET http://localhost:3000/payments/verify?reference=wy32tvrz7f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoibWFudWVsZ2VldGVjaEBnbWFpbC5jb20iLCJyb2xlIjoidmVuZG9yIiwiaWF0IjoxNzY0ODcyNDg0LCJleHAiOjE3NjQ4NzYwODQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Mgh35C30I2n9Jy206t96A7S0232_OsPQwEPVeGrf6tI