POST http://localhost:3000/withdrawals/request 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3Nzk3NDc0NywiZXhwIjoxNzc3OTc4MzQ3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.GQws8PpctTESP5mB7Lq72-wwMbJ6v0_9hpC18u8MEN0

{
    "amount": 3000
}

POST http://localhost:3000/withdrawals/finalize
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3NzcyMjM0NywiZXhwIjoxNzc3NzI1OTQ3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.5ryC7z75kEBt9s28EIbSPUeOt_RbNBa0jAXksMyF1Do
Content-Type: application/json

{
    "transferCode": "TRF_1u8dmnerq6yg34z9",
    "otp": "303693"
}