POST http://localhost:3000/withdrawals/request 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3NzMxMDczMCwiZXhwIjoxNzc3MzE0MzMwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rKUGuUlWYSb2eVX6s6A8UDBBsTnI8DxMap59jKsnvCg

{
    "amount": 2000
}

POST http://localhost:3000/withdrawals/finalize
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3NzMxMDczMCwiZXhwIjoxNzc3MzE0MzMwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.rKUGuUlWYSb2eVX6s6A8UDBBsTnI8DxMap59jKsnvCg
Content-Type: application/json

{
    "transferCode": "TRF_pqyyfptdidzgqn12",
    "otp": "076031"
}