POST http://localhost:3000/withdrawals/request 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3NzYyNzU1MywiZXhwIjoxNzc3NjMxMTUzLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.taWeY1t1enYgNm_Zx2HMSpeK0pWatUC1-tAM4OHWE3E

{
    "amount": 1000
}

POST http://localhost:3000/withdrawals/finalize
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3NzYyNzU1MywiZXhwIjoxNzc3NjMxMTUzLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.taWeY1t1enYgNm_Zx2HMSpeK0pWatUC1-tAM4OHWE3E
Content-Type: application/json

{
    "transferCode": "TRF_o0sgimxyt7sbs9ei",
    "otp": "761532"
}