POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Cole",
    "lastName": "Palmer",
    "email": "manuelgeetech@gmail.com",
    "phone": "09099090009",
    "password": "securePassword_123",
    "role": "agent"
}

POST http://localhost:3000/users/resend-signup-code
Content-Type: application/json

{
    "email": "manuelgeetech@gmail.com"
}


POST http://localhost:3000/users/verify-email
Content-Type: application/json

{
    "email": "manuelgeetech@gmail.com",
    "code": "151962"
}