GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huZG9lQHRlc3QuY29tIiwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNzU5ODYxMDYxLCJleHAiOjE3NTk4NjQ2NjEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.WpBWBD35nbHEDUudnF3a6LVv_H1WCpFIDHFk9RNIY3Y

GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3Nzk3MDY0OCwiZXhwIjoxNzc3OTc0MjQ4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.DKaW8rNcnWLMA0qsDIs_ltmai3X84s42ZX_uLYI-rJU