GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huZG9lQHRlc3QuY29tIiwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNzU5ODYxMDYxLCJleHAiOjE3NTk4NjQ2NjEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.WpBWBD35nbHEDUudnF3a6LVv_H1WCpFIDHFk9RNIY3Y