GET http://localhost:3000/verifications/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoid2V4bGVya2ltYmVybHk5MEBnbWFpbC5jb20iLCJpc0FnZW50IjpmYWxzZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJ2ZW5kb3IiLCJpYXQiOjE3NzkyNjIzNzAsImV4cCI6MTc3OTI2NTk3MCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.hAnKBus6FeA06Z6o05AySAFmIYKEfSXnrplYoDWjImI