GET http://localhost:3000/dispute
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoid2V4bGVya2ltYmVybHk5MEBnbWFpbC5jb20iLCJpc0FnZW50IjpmYWxzZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJ2ZW5kb3IiLCJpYXQiOjE3NzkyMTgzMDgsImV4cCI6MTc3OTIyMTkwOCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.T7wIZF9ju2ndebWsXNCx6KG97RDKWpudysofVyO0dJ4

GET http://localhost:3000/dispute
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoiZW1tYW51ZWxAZGlsaXZhbHkuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOmZhbHNlLCJhY3RpdmVSb2xlIjoiYWdlbnQiLCJpYXQiOjE3NzkyMTgwMDksImV4cCI6MTc3OTIyMTYwOSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.BWRdB3Xxki-xtQ0pUECasWrE3TgQh8rTSirXnNJS_LY


GET http://localhost:3000/dispute/2/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoiZW1tYW51ZWxAZGlsaXZhbHkuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOmZhbHNlLCJhY3RpdmVSb2xlIjoiYWdlbnQiLCJpYXQiOjE3NzkyMTgwMDksImV4cCI6MTc3OTIyMTYwOSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.BWRdB3Xxki-xtQ0pUECasWrE3TgQh8rTSirXnNJS_LY

GET http://localhost:3000/dispute/2/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoid2V4bGVya2ltYmVybHk5MEBnbWFpbC5jb20iLCJpc0FnZW50IjpmYWxzZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJ2ZW5kb3IiLCJpYXQiOjE3NzkyMTgzMDgsImV4cCI6MTc3OTIyMTkwOCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.T7wIZF9ju2ndebWsXNCx6KG97RDKWpudysofVyO0dJ4