POST http://localhost:3000/delivery-request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6ZmFsc2UsImlzVmVuZG9yIjp0cnVlLCJpYXQiOjE3NjgzMDYxMDksImV4cCI6MTc2ODMwOTcwOSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.twrOpeDyX25pb0B9Uigaat9r7VchawnDTC010IfgAeE

{
    "title": "Imo Delivery Agent Needed",
    "description": "I need a reliable delivery agent in Imo for multiple deliveries",
    "state": "imo",
    "addresses": [
        { "address": "Lekki Phase 1, admiralty way Imo", "deliveryType": "prepaid" },
        { "address": "28, Isaac John stree, Ikeja GRA Imo", "deliveryType": "cod" }
    ]
}