POST http://localhost:3000/delivery-request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoibWFudWVsZ2VldGVjaEBnbWFpbC5jb20iLCJyb2xlIjoidmVuZG9yIiwiaWF0IjoxNzY0ODc0MTA3LCJleHAiOjE3NjQ4Nzc3MDcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.qUEavWRwPaLyvWCPOhXURmyMzPuGA-tpm3KdEWPZWNc

{
    "title": "Lagos Delivery Agent Needed",
    "description": "I need a reliable delivery agent in Lagos for multiple deliveries",
    "state": "Lagos",
    "addresses": [
        { "address": "Lekki Phase 1, admiralty way", "deliveryType": "prepaid" },
        { "address": "28, Isaac John stree, Ikeja GRA", "deliveryType": "cod" }
    ]
}