GET http://localhost:3000/delivery-request/available
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJvdGFpZ2JlZW1tYW51ZWwyMUBnbWFpbC5jb20iLCJyb2xlIjoiYWdlbnQiLCJpYXQiOjE3NjQ3NTk4MTQsImV4cCI6MTc2NDc2MzQxNCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.kg5g-PJYOJf75hMvn2HsPuk6mDr4hrFKlJyjmEd9bAY


GET http://localhost:3000/delivery-request/24
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwicm9sZSI6ImFnZW50IiwiaWF0IjoxNzY0NzU5Mjg1LCJleHAiOjE3NjQ3NjI4ODUsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.AiUHpV2mRtfeIruGlVTVP-GG37DmBpCK531c1h5hkBs


GET http://localhost:3000/delivery-request/order-summary/24
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoibWFudWVsZ2VldGVjaEBnbWFpbC5jb20iLCJyb2xlIjoidmVuZG9yIiwiaWF0IjoxNzY0NzU4OTEwLCJleHAiOjE3NjQ3NjI1MTAsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.0B1faXwOj3B00lx9QjNpj9PEWjICN8CnP7Fwe-INCvg