POST http://localhost:3000/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwicm9sZSI6ImFnZW50IiwiaWF0IjoxNzYzMTQ5ODQwLCJleHAiOjE3NjMxNTM0NDAsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.WI00fSwf-ukzhxLg8OOgw8ukegSHQG9JD1qnLQkX4tM

{
    "oldPassword": "Jesusmanug999",
    "newPassword": "Otaigbe@2025"
}