POST http://localhost:3000/auth/forgot-password 
Content-Type: application/json

{
    "email": "manugtech@gmail.com"
}


POST http://localhost:3000/auth/verify-reset-code 
Content-Type: application/json

{
    "email": "otaigbeemmanuel21@gmail.com",
    "code": "815700"
}


POST http://localhost:3000/auth/reset-password 
Content-Type: application/json

{
    "email": "otaigbeemmanuel21@gmail.com",
    "code": "815700",
    "newPassword": "Jesusmanug999"
}