POST http://localhost:3000/auth/sign-in 
Content-Type: application/json

{
    "email": "emmanuel@dilivaly.com",
    "password": "jesusmanug@999"
}


POST http://localhost:3000/auth/sign-in 
Content-Type: application/json

{
    "email": "lydiamcgill22@gmail.com",
    "password": "securePassword@123"
}