GET http://localhost:3000/reviews/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoibWFudWVsZ2VldGVjaEBnbWFpbC5jb20iLCJyb2xlIjoidmVuZG9yIiwiaWF0IjoxNzY0MzMwOTY2LCJleHAiOjE3NjQzMzQ1NjYsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.KbrPjVfItPKqAQEf1Uauvlraqgsl4nt8VjzgiP_r6pw