POST https://diliverly-backend.onrender.com/wallets/fund
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJseWRpYW1jZ2lsbDIyQGdtYWlsLmNvbSIsImlzQWdlbnQiOnRydWUsImlzVmVuZG9yIjpmYWxzZSwiYWN0aXZlUm9sZSI6ImFnZW50IiwiaWF0IjoxNzc2OTcyMDc2LCJleHAiOjE3NzY5NzU2NzYsImF1ZCI6Imh0dHBzOi8vZGlsaXZlcmx5LWJhY2tlbmQub25yZW5kZXIuY29tIiwiaXNzIjoiaHR0cHM6Ly9kaWxpdmVybHktYmFja2VuZC5vbnJlbmRlci5jb20ifQ.XL4yJdJ4rKvvbKxokJxbbIH39yhqIVXAIWJR2RCHDuI

{
    "amount": 30000
}