POST https://diliverly-backend.onrender.com/wallets/fund
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJseWRpYW1jZ2lsbDIyQGdtYWlsLmNvbSIsImlzQWdlbnQiOnRydWUsImlzVmVuZG9yIjpmYWxzZSwiYWN0aXZlUm9sZSI6ImFnZW50IiwiaWF0IjoxNzc3MDE3MzY3LCJleHAiOjE3NzcwMjA5NjcsImF1ZCI6Imh0dHBzOi8vZGlsaXZlcmx5LWJhY2tlbmQub25yZW5kZXIuY29tIiwiaXNzIjoiaHR0cHM6Ly9kaWxpdmVybHktYmFja2VuZC5vbnJlbmRlci5jb20ifQ.N4JwcPqdG03cxrBv1lpvfjFhn8SVZ3r0phvA6Y81tr0

{
    "amount": 30000
}


POST https://diliverly-backend.onrender.com/wallets/webhook/paystack
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJseWRpYW1jZ2lsbDIyQGdtYWlsLmNvbSIsImlzQWdlbnQiOnRydWUsImlzVmVuZG9yIjpmYWxzZSwiYWN0aXZlUm9sZSI6ImFnZW50IiwiaWF0IjoxNzc3MDE3MzY3LCJleHAiOjE3NzcwMjA5NjcsImF1ZCI6Imh0dHBzOi8vZGlsaXZlcmx5LWJhY2tlbmQub25yZW5kZXIuY29tIiwiaXNzIjoiaHR0cHM6Ly9kaWxpdmVybHktYmFja2VuZC5vbnJlbmRlci5jb20ifQ.N4JwcPqdG03cxrBv1lpvfjFhn8SVZ3r0phvA6Y81tr0