POST http://localhost:3000/orders/create-order-items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3NzAzMjI3MiwiZXhwIjoxNzc3MDM1ODcyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.jnubvpma3oUWiwR74bhcZeZjC4VuaR13r1gHow6w0QY

{
    "requestId": 22,
    "items": [
        {
            "deliveryId": 69,
            "itemName": "Wireless Mouse",
            "quantity": 2,
            "buyerName": "John Doe",
            "buyerPhone": "+1234567890"
        },
        {
            "deliveryId": 70,
            "itemName": "Keyboard",
            "quantity": 1,
            "buyerName": "Jane Smith",
            "buyerPhone": "+0987654321",
            "codAmount": 1000
        },
        {
            "deliveryId": 71,
            "itemName": "USB-C Cable",
            "quantity": 3,
            "buyerName": "Alice Johnson",
            "buyerPhone": "+1122334455",
            "codAmount": 1500
        },
        {
            "deliveryId": 72,
            "itemName": "USB-C Cable",
            "quantity": 3,
            "buyerName": "Alice Johnson",
            "buyerPhone": "+1122334455",
            "codAmount": 1500
        }
    ]
}

POST http://localhost:3000/orders/mark-delivered
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJseWRpYW1jZ2lsbDIyQGdtYWlsLmNvbSIsImlzQWdlbnQiOnRydWUsImlzVmVuZG9yIjpmYWxzZSwiYWN0aXZlUm9sZSI6ImFnZW50IiwiaWF0IjoxNzc3MDMyOTIzLCJleHAiOjE3NzcwMzY1MjMsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.6vLxu1TpuKmaPkA6YHl1BEyLVo5KR8ro_lcA3gUYHXg

{
    "orderItemId": 37,
    "deliveryPin": "5519"
}


POST http://localhost:3000/orders/cancel-order-item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJseWRpYW1jZ2lsbDIyQGdtYWlsLmNvbSIsImlzQWdlbnQiOnRydWUsImlzVmVuZG9yIjpmYWxzZSwiYWN0aXZlUm9sZSI6ImFnZW50IiwiaWF0IjoxNzc3MDMyOTIzLCJleHAiOjE3NzcwMzY1MjMsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.6vLxu1TpuKmaPkA6YHl1BEyLVo5KR8ro_lcA3gUYHXg

{
    "orderItemId": 39
}