GET http://localhost:3000/orders/agent/my-orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3NzA0MjEwNCwiZXhwIjoxNzc3MDQ1NzA0LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.3nl5EZnauN5DUlB83aa8T0_ryoVHS5ltC-4QmzXeXYo


GET http://localhost:3000/orders/vendor/my-orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3NzQ3NDEyNiwiZXhwIjoxNzc3NDc3NzI2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.zEmeUhuQik0yO8DDt3Z2KwKzQ9mc-6aeKqNxp25-3Po


GET http://localhost:3000/orders/10/items  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJtb2lAdGVzdC5jb20iLCJyb2xlIjoiYWdlbnQiLCJpYXQiOjE3NjI0NTY5NzAsImV4cCI6MTc2MjQ2MDU3MCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.AwRbTGQ2G5W9ylQDXs4_Kp2iACoRiG46jaNPmX-bZo8

