GET http://localhost:3000/orders/agent/my-orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwicm9sZSI6ImFnZW50IiwiaWF0IjoxNzYzNDA4NzM0LCJleHAiOjE3NjM0MTIzMzQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.WCCaMA6vfsyiRcTWKS1ol6k_fSmUjeVS0O-hxLewR_w


GET http://localhost:3000/orders/vendor/my-orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6dHJ1ZSwiaXNWZW5kb3IiOnRydWUsImFjdGl2ZVJvbGUiOiJhZ2VudCIsImlhdCI6MTc3NjI1NzEyOCwiZXhwIjoxNzc2MjYwNzI4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.I8hJvGldSQL5r_D051i4pCbAdq-0_ano9BpRUM9uk0Y


GET http://localhost:3000/orders/10/items  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJtb2lAdGVzdC5jb20iLCJyb2xlIjoiYWdlbnQiLCJpYXQiOjE3NjI0NTY5NzAsImV4cCI6MTc2MjQ2MDU3MCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.AwRbTGQ2G5W9ylQDXs4_Kp2iACoRiG46jaNPmX-bZo8

