POST http://localhost:3000/orders/create-order-items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6ZmFsc2UsImlzVmVuZG9yIjp0cnVlLCJpYXQiOjE3NzEzNDU4NjMsImV4cCI6MTc3MTM0OTQ2MywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.rshe-kNJoAbTMHnj0JJgxLJ9h-EmPs8G1x4_5fCU8mM

{
    "requestId": 4,
    "items": [
        {
            "itemName": "Wireless Mouse",
            "quantity": 2,
            "buyerName": "John Doe",
            "buyerPhone": "+1234567890"
        },
        {
            "itemName": "Keyboard",
            "quantity": 1,
            "buyerName": "Jane Smith",
            "buyerPhone": "+0987654321",
            "codAmount": 20000
        },
        {
            "itemName": "USB-C Cable",
            "quantity": 3,
            "buyerName": "Alice Johnson",
            "buyerPhone": "+1122334455",
            "codAmount": 25000
        },
        {
            "itemName": "Laptop Stand",
            "quantity": 1,
            "buyerName": "Bob Brown",
            "buyerPhone": "+5566778899",
            "codAmount": 15000
        }
    ]
}

POST http://localhost:3000/orders/mark-delivered
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJseWRpYW1jZ2lsbDIyQGdtYWlsLmNvbSIsImlzQWdlbnQiOnRydWUsImlzVmVuZG9yIjpmYWxzZSwiaWF0IjoxNzcxMzQ3MzY2LCJleHAiOjE3NzEzNTA5NjYsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.KgMNwHnOw6kcIEeaQuUZuUsIXRkuPAodhT6WDNoRTFk

{
    "orderItemId": 7,
    "deliveryPin": "9915"
}


POST http://localhost:3000/orders/cancel-order-item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJseWRpYW1jZ2lsbDIyQGdtYWlsLmNvbSIsImlzQWdlbnQiOnRydWUsImlzVmVuZG9yIjpmYWxzZSwiaWF0IjoxNzcxMzQ3MzY2LCJleHAiOjE3NzEzNTA5NjYsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.KgMNwHnOw6kcIEeaQuUZuUsIXRkuPAodhT6WDNoRTFk

{
    "orderItemId": 8
}