GET http://localhost:3000/paystack/verify?reference=FUND-D7322551822AV
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYW51Z3RlY2hAZ21haWwuY29tIiwiaXNBZ2VudCI6ZmFsc2UsImlzVmVuZG9yIjp0cnVlLCJpYXQiOjE3NzA5OTc4NjcsImV4cCI6MTc3MTAwMTQ2NywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.09IgQhiRsB5yQwkEFG2QzHE4ifVKCvr0feU92gCM72c